// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Client/AuditScReq.proto

package Client

import (
	Enum "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Enum"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditScReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         Enum.AuditEvents       `protobuf:"varint,1,opt,name=Event,proto3,enum=ClassIsland.Shared.Protobuf.Enum.AuditEvents" json:"Event,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	TimestampUtc  int64                  `protobuf:"varint,3,opt,name=TimestampUtc,proto3" json:"TimestampUtc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditScReq) Reset() {
	*x = AuditScReq{}
	mi := &file_Protobuf_Client_AuditScReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditScReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditScReq) ProtoMessage() {}

func (x *AuditScReq) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_Client_AuditScReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditScReq.ProtoReflect.Descriptor instead.
func (*AuditScReq) Descriptor() ([]byte, []int) {
	return file_Protobuf_Client_AuditScReq_proto_rawDescGZIP(), []int{0}
}

func (x *AuditScReq) GetEvent() Enum.AuditEvents {
	if x != nil {
		return x.Event
	}
	return Enum.AuditEvents(0)
}

func (x *AuditScReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuditScReq) GetTimestampUtc() int64 {
	if x != nil {
		return x.TimestampUtc
	}
	return 0
}

var File_Protobuf_Client_AuditScReq_proto protoreflect.FileDescriptor

const file_Protobuf_Client_AuditScReq_proto_rawDesc = "" +
	"\n" +
	" Protobuf/Client/AuditScReq.proto\x12\"ClassIsland.Shared.Protobuf.Client\x1a\x1fProtobuf/Enum/AuditEvents.proto\"\x8f\x01\n" +
	"\n" +
	"AuditScReq\x12C\n" +
	"\x05Event\x18\x01 \x01(\x0e2-.ClassIsland.Shared.Protobuf.Enum.AuditEventsR\x05Event\x12\x18\n" +
	"\aPayload\x18\x02 \x01(\fR\aPayload\x12\"\n" +
	"\fTimestampUtc\x18\x03 \x01(\x03R\fTimestampUtcB%\xaa\x02\"ClassIsland.Shared.Protobuf.Clientb\x06proto3"

var (
	file_Protobuf_Client_AuditScReq_proto_rawDescOnce sync.Once
	file_Protobuf_Client_AuditScReq_proto_rawDescData []byte
)

func file_Protobuf_Client_AuditScReq_proto_rawDescGZIP() []byte {
	file_Protobuf_Client_AuditScReq_proto_rawDescOnce.Do(func() {
		file_Protobuf_Client_AuditScReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_Client_AuditScReq_proto_rawDesc), len(file_Protobuf_Client_AuditScReq_proto_rawDesc)))
	})
	return file_Protobuf_Client_AuditScReq_proto_rawDescData
}

var file_Protobuf_Client_AuditScReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Protobuf_Client_AuditScReq_proto_goTypes = []any{
	(*AuditScReq)(nil),    // 0: ClassIsland.Shared.Protobuf.Client.AuditScReq
	(Enum.AuditEvents)(0), // 1: ClassIsland.Shared.Protobuf.Enum.AuditEvents
}
var file_Protobuf_Client_AuditScReq_proto_depIdxs = []int32{
	1, // 0: ClassIsland.Shared.Protobuf.Client.AuditScReq.Event:type_name -> ClassIsland.Shared.Protobuf.Enum.AuditEvents
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Protobuf_Client_AuditScReq_proto_init() }
func file_Protobuf_Client_AuditScReq_proto_init() {
	if File_Protobuf_Client_AuditScReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Client_AuditScReq_proto_rawDesc), len(file_Protobuf_Client_AuditScReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_Client_AuditScReq_proto_goTypes,
		DependencyIndexes: file_Protobuf_Client_AuditScReq_proto_depIdxs,
		MessageInfos:      file_Protobuf_Client_AuditScReq_proto_msgTypes,
	}.Build()
	File_Protobuf_Client_AuditScReq_proto = out.File
	file_Protobuf_Client_AuditScReq_proto_goTypes = nil
	file_Protobuf_Client_AuditScReq_proto_depIdxs = nil
}
