// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Client/ClientRegisterCsReq.proto

package Client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientRegisterCsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientUid     string                 `protobuf:"bytes,1,opt,name=ClientUid,proto3" json:"ClientUid,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	ClientMac     string                 `protobuf:"bytes,3,opt,name=ClientMac,proto3" json:"ClientMac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRegisterCsReq) Reset() {
	*x = ClientRegisterCsReq{}
	mi := &file_Protobuf_Client_ClientRegisterCsReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRegisterCsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegisterCsReq) ProtoMessage() {}

func (x *ClientRegisterCsReq) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_Client_ClientRegisterCsReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegisterCsReq.ProtoReflect.Descriptor instead.
func (*ClientRegisterCsReq) Descriptor() ([]byte, []int) {
	return file_Protobuf_Client_ClientRegisterCsReq_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRegisterCsReq) GetClientUid() string {
	if x != nil {
		return x.ClientUid
	}
	return ""
}

func (x *ClientRegisterCsReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientRegisterCsReq) GetClientMac() string {
	if x != nil {
		return x.ClientMac
	}
	return ""
}

var File_Protobuf_Client_ClientRegisterCsReq_proto protoreflect.FileDescriptor

const file_Protobuf_Client_ClientRegisterCsReq_proto_rawDesc = "" +
	"\n" +
	")Protobuf/Client/ClientRegisterCsReq.proto\x12\"ClassIsland.Shared.Protobuf.Client\"m\n" +
	"\x13ClientRegisterCsReq\x12\x1c\n" +
	"\tClientUid\x18\x01 \x01(\tR\tClientUid\x12\x1a\n" +
	"\bClientId\x18\x02 \x01(\tR\bClientId\x12\x1c\n" +
	"\tClientMac\x18\x03 \x01(\tR\tClientMacB%\xaa\x02\"ClassIsland.Shared.Protobuf.Clientb\x06proto3"

var (
	file_Protobuf_Client_ClientRegisterCsReq_proto_rawDescOnce sync.Once
	file_Protobuf_Client_ClientRegisterCsReq_proto_rawDescData []byte
)

func file_Protobuf_Client_ClientRegisterCsReq_proto_rawDescGZIP() []byte {
	file_Protobuf_Client_ClientRegisterCsReq_proto_rawDescOnce.Do(func() {
		file_Protobuf_Client_ClientRegisterCsReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_Client_ClientRegisterCsReq_proto_rawDesc), len(file_Protobuf_Client_ClientRegisterCsReq_proto_rawDesc)))
	})
	return file_Protobuf_Client_ClientRegisterCsReq_proto_rawDescData
}

var file_Protobuf_Client_ClientRegisterCsReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Protobuf_Client_ClientRegisterCsReq_proto_goTypes = []any{
	(*ClientRegisterCsReq)(nil), // 0: ClassIsland.Shared.Protobuf.Client.ClientRegisterCsReq
}
var file_Protobuf_Client_ClientRegisterCsReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_Client_ClientRegisterCsReq_proto_init() }
func file_Protobuf_Client_ClientRegisterCsReq_proto_init() {
	if File_Protobuf_Client_ClientRegisterCsReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Client_ClientRegisterCsReq_proto_rawDesc), len(file_Protobuf_Client_ClientRegisterCsReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_Client_ClientRegisterCsReq_proto_goTypes,
		DependencyIndexes: file_Protobuf_Client_ClientRegisterCsReq_proto_depIdxs,
		MessageInfos:      file_Protobuf_Client_ClientRegisterCsReq_proto_msgTypes,
	}.Build()
	File_Protobuf_Client_ClientRegisterCsReq_proto = out.File
	file_Protobuf_Client_ClientRegisterCsReq_proto_goTypes = nil
	file_Protobuf_Client_ClientRegisterCsReq_proto_depIdxs = nil
}
