// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Client/ClientCommandDeliverScReq.proto

package Client

import (
	Enum "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Enum"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientCommandDeliverScReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Enum.CommandTypes      `protobuf:"varint,2,opt,name=Type,proto3,enum=ClassIsland.Shared.Protobuf.Enum.CommandTypes" json:"Type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCommandDeliverScReq) Reset() {
	*x = ClientCommandDeliverScReq{}
	mi := &file_Protobuf_Client_ClientCommandDeliverScReq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCommandDeliverScReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCommandDeliverScReq) ProtoMessage() {}

func (x *ClientCommandDeliverScReq) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_Client_ClientCommandDeliverScReq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCommandDeliverScReq.ProtoReflect.Descriptor instead.
func (*ClientCommandDeliverScReq) Descriptor() ([]byte, []int) {
	return file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDescGZIP(), []int{0}
}

func (x *ClientCommandDeliverScReq) GetType() Enum.CommandTypes {
	if x != nil {
		return x.Type
	}
	return Enum.CommandTypes(0)
}

func (x *ClientCommandDeliverScReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_Protobuf_Client_ClientCommandDeliverScReq_proto protoreflect.FileDescriptor

const file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDesc = "" +
	"\n" +
	"/Protobuf/Client/ClientCommandDeliverScReq.proto\x12\"ClassIsland.Shared.Protobuf.Client\x1a Protobuf/Enum/CommandTypes.proto\"y\n" +
	"\x19ClientCommandDeliverScReq\x12B\n" +
	"\x04Type\x18\x02 \x01(\x0e2..ClassIsland.Shared.Protobuf.Enum.CommandTypesR\x04Type\x12\x18\n" +
	"\aPayload\x18\x03 \x01(\fR\aPayloadB%\xaa\x02\"ClassIsland.Shared.Protobuf.Clientb\x06proto3"

var (
	file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDescOnce sync.Once
	file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDescData []byte
)

func file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDescGZIP() []byte {
	file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDescOnce.Do(func() {
		file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDesc), len(file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDesc)))
	})
	return file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDescData
}

var file_Protobuf_Client_ClientCommandDeliverScReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Protobuf_Client_ClientCommandDeliverScReq_proto_goTypes = []any{
	(*ClientCommandDeliverScReq)(nil), // 0: ClassIsland.Shared.Protobuf.Client.ClientCommandDeliverScReq
	(Enum.CommandTypes)(0),            // 1: ClassIsland.Shared.Protobuf.Enum.CommandTypes
}
var file_Protobuf_Client_ClientCommandDeliverScReq_proto_depIdxs = []int32{
	1, // 0: ClassIsland.Shared.Protobuf.Client.ClientCommandDeliverScReq.Type:type_name -> ClassIsland.Shared.Protobuf.Enum.CommandTypes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Protobuf_Client_ClientCommandDeliverScReq_proto_init() }
func file_Protobuf_Client_ClientCommandDeliverScReq_proto_init() {
	if File_Protobuf_Client_ClientCommandDeliverScReq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDesc), len(file_Protobuf_Client_ClientCommandDeliverScReq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_Client_ClientCommandDeliverScReq_proto_goTypes,
		DependencyIndexes: file_Protobuf_Client_ClientCommandDeliverScReq_proto_depIdxs,
		MessageInfos:      file_Protobuf_Client_ClientCommandDeliverScReq_proto_msgTypes,
	}.Build()
	File_Protobuf_Client_ClientCommandDeliverScReq_proto = out.File
	file_Protobuf_Client_ClientCommandDeliverScReq_proto_goTypes = nil
	file_Protobuf_Client_ClientCommandDeliverScReq_proto_depIdxs = nil
}
