// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Enum/AuditEvents.proto

package Enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEvents int32

const (
	AuditEvents_DefaultEvent     AuditEvents = 0
	AuditEvents_AuthorizeSuccess AuditEvents = 1
	AuditEvents_AuthorizeFailed  AuditEvents = 2
	// AuthorizeCanceled = 3;
	AuditEvents_AppSettingsUpdated   AuditEvents = 4
	AuditEvents_ClassChangeCompleted AuditEvents = 5
	AuditEvents_ClassPlanUpdated     AuditEvents = 6
	AuditEvents_TimeLayoutUpdated    AuditEvents = 7
	AuditEvents_SubjectUpdated       AuditEvents = 8
	AuditEvents_AppCrashed           AuditEvents = 9
	AuditEvents_AppStarted           AuditEvents = 10
	AuditEvents_AppExited            AuditEvents = 11
	AuditEvents_PluginInstalled      AuditEvents = 12
	AuditEvents_PluginUninstalled    AuditEvents = 13
)

// Enum value maps for AuditEvents.
var (
	AuditEvents_name = map[int32]string{
		0:  "DefaultEvent",
		1:  "AuthorizeSuccess",
		2:  "AuthorizeFailed",
		4:  "AppSettingsUpdated",
		5:  "ClassChangeCompleted",
		6:  "ClassPlanUpdated",
		7:  "TimeLayoutUpdated",
		8:  "SubjectUpdated",
		9:  "AppCrashed",
		10: "AppStarted",
		11: "AppExited",
		12: "PluginInstalled",
		13: "PluginUninstalled",
	}
	AuditEvents_value = map[string]int32{
		"DefaultEvent":         0,
		"AuthorizeSuccess":     1,
		"AuthorizeFailed":      2,
		"AppSettingsUpdated":   4,
		"ClassChangeCompleted": 5,
		"ClassPlanUpdated":     6,
		"TimeLayoutUpdated":    7,
		"SubjectUpdated":       8,
		"AppCrashed":           9,
		"AppStarted":           10,
		"AppExited":            11,
		"PluginInstalled":      12,
		"PluginUninstalled":    13,
	}
)

func (x AuditEvents) Enum() *AuditEvents {
	p := new(AuditEvents)
	*p = x
	return p
}

func (x AuditEvents) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEvents) Descriptor() protoreflect.EnumDescriptor {
	return file_Protobuf_Enum_AuditEvents_proto_enumTypes[0].Descriptor()
}

func (AuditEvents) Type() protoreflect.EnumType {
	return &file_Protobuf_Enum_AuditEvents_proto_enumTypes[0]
}

func (x AuditEvents) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEvents.Descriptor instead.
func (AuditEvents) EnumDescriptor() ([]byte, []int) {
	return file_Protobuf_Enum_AuditEvents_proto_rawDescGZIP(), []int{0}
}

var File_Protobuf_Enum_AuditEvents_proto protoreflect.FileDescriptor

const file_Protobuf_Enum_AuditEvents_proto_rawDesc = "" +
	"\n" +
	"\x1fProtobuf/Enum/AuditEvents.proto\x12 ClassIsland.Shared.Protobuf.Enum*\x98\x02\n" +
	"\vAuditEvents\x12\x10\n" +
	"\fDefaultEvent\x10\x00\x12\x14\n" +
	"\x10AuthorizeSuccess\x10\x01\x12\x13\n" +
	"\x0fAuthorizeFailed\x10\x02\x12\x16\n" +
	"\x12AppSettingsUpdated\x10\x04\x12\x18\n" +
	"\x14ClassChangeCompleted\x10\x05\x12\x14\n" +
	"\x10ClassPlanUpdated\x10\x06\x12\x15\n" +
	"\x11TimeLayoutUpdated\x10\a\x12\x12\n" +
	"\x0eSubjectUpdated\x10\b\x12\x0e\n" +
	"\n" +
	"AppCrashed\x10\t\x12\x0e\n" +
	"\n" +
	"AppStarted\x10\n" +
	"\x12\r\n" +
	"\tAppExited\x10\v\x12\x13\n" +
	"\x0fPluginInstalled\x10\f\x12\x15\n" +
	"\x11PluginUninstalled\x10\rB#\xaa\x02 ClassIsland.Shared.Protobuf.Enumb\x06proto3"

var (
	file_Protobuf_Enum_AuditEvents_proto_rawDescOnce sync.Once
	file_Protobuf_Enum_AuditEvents_proto_rawDescData []byte
)

func file_Protobuf_Enum_AuditEvents_proto_rawDescGZIP() []byte {
	file_Protobuf_Enum_AuditEvents_proto_rawDescOnce.Do(func() {
		file_Protobuf_Enum_AuditEvents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_Enum_AuditEvents_proto_rawDesc), len(file_Protobuf_Enum_AuditEvents_proto_rawDesc)))
	})
	return file_Protobuf_Enum_AuditEvents_proto_rawDescData
}

var file_Protobuf_Enum_AuditEvents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Protobuf_Enum_AuditEvents_proto_goTypes = []any{
	(AuditEvents)(0), // 0: ClassIsland.Shared.Protobuf.Enum.AuditEvents
}
var file_Protobuf_Enum_AuditEvents_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_Enum_AuditEvents_proto_init() }
func file_Protobuf_Enum_AuditEvents_proto_init() {
	if File_Protobuf_Enum_AuditEvents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Enum_AuditEvents_proto_rawDesc), len(file_Protobuf_Enum_AuditEvents_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_Enum_AuditEvents_proto_goTypes,
		DependencyIndexes: file_Protobuf_Enum_AuditEvents_proto_depIdxs,
		EnumInfos:         file_Protobuf_Enum_AuditEvents_proto_enumTypes,
	}.Build()
	File_Protobuf_Enum_AuditEvents_proto = out.File
	file_Protobuf_Enum_AuditEvents_proto_goTypes = nil
	file_Protobuf_Enum_AuditEvents_proto_depIdxs = nil
}
