// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Enum/CommandTypes.proto

package Enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandTypes int32

const (
	CommandTypes_DefaultCommand CommandTypes = 0
	// Misc
	// Heartbeat
	CommandTypes_Ping CommandTypes = 10
	CommandTypes_Pong CommandTypes = 11
	// MiscCommands
	CommandTypes_RestartApp       CommandTypes = 101
	CommandTypes_SendNotification CommandTypes = 102
	CommandTypes_DataUpdated      CommandTypes = 103
	CommandTypes_GetClientConfig  CommandTypes = 104
)

// Enum value maps for CommandTypes.
var (
	CommandTypes_name = map[int32]string{
		0:   "DefaultCommand",
		10:  "Ping",
		11:  "Pong",
		101: "RestartApp",
		102: "SendNotification",
		103: "DataUpdated",
		104: "GetClientConfig",
	}
	CommandTypes_value = map[string]int32{
		"DefaultCommand":   0,
		"Ping":             10,
		"Pong":             11,
		"RestartApp":       101,
		"SendNotification": 102,
		"DataUpdated":      103,
		"GetClientConfig":  104,
	}
)

func (x CommandTypes) Enum() *CommandTypes {
	p := new(CommandTypes)
	*p = x
	return p
}

func (x CommandTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_Protobuf_Enum_CommandTypes_proto_enumTypes[0].Descriptor()
}

func (CommandTypes) Type() protoreflect.EnumType {
	return &file_Protobuf_Enum_CommandTypes_proto_enumTypes[0]
}

func (x CommandTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandTypes.Descriptor instead.
func (CommandTypes) EnumDescriptor() ([]byte, []int) {
	return file_Protobuf_Enum_CommandTypes_proto_rawDescGZIP(), []int{0}
}

var File_Protobuf_Enum_CommandTypes_proto protoreflect.FileDescriptor

const file_Protobuf_Enum_CommandTypes_proto_rawDesc = "" +
	"\n" +
	" Protobuf/Enum/CommandTypes.proto\x12 ClassIsland.Shared.Protobuf.Enum*\x82\x01\n" +
	"\fCommandTypes\x12\x12\n" +
	"\x0eDefaultCommand\x10\x00\x12\b\n" +
	"\x04Ping\x10\n" +
	"\x12\b\n" +
	"\x04Pong\x10\v\x12\x0e\n" +
	"\n" +
	"RestartApp\x10e\x12\x14\n" +
	"\x10SendNotification\x10f\x12\x0f\n" +
	"\vDataUpdated\x10g\x12\x13\n" +
	"\x0fGetClientConfig\x10hB#\xaa\x02 ClassIsland.Shared.Protobuf.Enumb\x06proto3"

var (
	file_Protobuf_Enum_CommandTypes_proto_rawDescOnce sync.Once
	file_Protobuf_Enum_CommandTypes_proto_rawDescData []byte
)

func file_Protobuf_Enum_CommandTypes_proto_rawDescGZIP() []byte {
	file_Protobuf_Enum_CommandTypes_proto_rawDescOnce.Do(func() {
		file_Protobuf_Enum_CommandTypes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_Enum_CommandTypes_proto_rawDesc), len(file_Protobuf_Enum_CommandTypes_proto_rawDesc)))
	})
	return file_Protobuf_Enum_CommandTypes_proto_rawDescData
}

var file_Protobuf_Enum_CommandTypes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Protobuf_Enum_CommandTypes_proto_goTypes = []any{
	(CommandTypes)(0), // 0: ClassIsland.Shared.Protobuf.Enum.CommandTypes
}
var file_Protobuf_Enum_CommandTypes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_Enum_CommandTypes_proto_init() }
func file_Protobuf_Enum_CommandTypes_proto_init() {
	if File_Protobuf_Enum_CommandTypes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Enum_CommandTypes_proto_rawDesc), len(file_Protobuf_Enum_CommandTypes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_Enum_CommandTypes_proto_goTypes,
		DependencyIndexes: file_Protobuf_Enum_CommandTypes_proto_depIdxs,
		EnumInfos:         file_Protobuf_Enum_CommandTypes_proto_enumTypes,
	}.Build()
	File_Protobuf_Enum_CommandTypes_proto = out.File
	file_Protobuf_Enum_CommandTypes_proto_goTypes = nil
	file_Protobuf_Enum_CommandTypes_proto_depIdxs = nil
}
