// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Enum/ConfigTypes.proto

package Enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigTypes int32

const (
	ConfigTypes_UnspecifiedConfig ConfigTypes = 0
	ConfigTypes_AppSettings       ConfigTypes = 1
	ConfigTypes_Profile           ConfigTypes = 2
	ConfigTypes_CurrentComponent  ConfigTypes = 3
	ConfigTypes_CurrentAutomation ConfigTypes = 4
	ConfigTypes_Logs              ConfigTypes = 5
	ConfigTypes_PluginList        ConfigTypes = 6
)

// Enum value maps for ConfigTypes.
var (
	ConfigTypes_name = map[int32]string{
		0: "UnspecifiedConfig",
		1: "AppSettings",
		2: "Profile",
		3: "CurrentComponent",
		4: "CurrentAutomation",
		5: "Logs",
		6: "PluginList",
	}
	ConfigTypes_value = map[string]int32{
		"UnspecifiedConfig": 0,
		"AppSettings":       1,
		"Profile":           2,
		"CurrentComponent":  3,
		"CurrentAutomation": 4,
		"Logs":              5,
		"PluginList":        6,
	}
)

func (x ConfigTypes) Enum() *ConfigTypes {
	p := new(ConfigTypes)
	*p = x
	return p
}

func (x ConfigTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_Protobuf_Enum_ConfigTypes_proto_enumTypes[0].Descriptor()
}

func (ConfigTypes) Type() protoreflect.EnumType {
	return &file_Protobuf_Enum_ConfigTypes_proto_enumTypes[0]
}

func (x ConfigTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigTypes.Descriptor instead.
func (ConfigTypes) EnumDescriptor() ([]byte, []int) {
	return file_Protobuf_Enum_ConfigTypes_proto_rawDescGZIP(), []int{0}
}

var File_Protobuf_Enum_ConfigTypes_proto protoreflect.FileDescriptor

const file_Protobuf_Enum_ConfigTypes_proto_rawDesc = "" +
	"\n" +
	"\x1fProtobuf/Enum/ConfigTypes.proto\x12 ClassIsland.Shared.Protobuf.Enum*\x89\x01\n" +
	"\vConfigTypes\x12\x15\n" +
	"\x11UnspecifiedConfig\x10\x00\x12\x0f\n" +
	"\vAppSettings\x10\x01\x12\v\n" +
	"\aProfile\x10\x02\x12\x14\n" +
	"\x10CurrentComponent\x10\x03\x12\x15\n" +
	"\x11CurrentAutomation\x10\x04\x12\b\n" +
	"\x04Logs\x10\x05\x12\x0e\n" +
	"\n" +
	"PluginList\x10\x06B#\xaa\x02 ClassIsland.Shared.Protobuf.Enumb\x06proto3"

var (
	file_Protobuf_Enum_ConfigTypes_proto_rawDescOnce sync.Once
	file_Protobuf_Enum_ConfigTypes_proto_rawDescData []byte
)

func file_Protobuf_Enum_ConfigTypes_proto_rawDescGZIP() []byte {
	file_Protobuf_Enum_ConfigTypes_proto_rawDescOnce.Do(func() {
		file_Protobuf_Enum_ConfigTypes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_Enum_ConfigTypes_proto_rawDesc), len(file_Protobuf_Enum_ConfigTypes_proto_rawDesc)))
	})
	return file_Protobuf_Enum_ConfigTypes_proto_rawDescData
}

var file_Protobuf_Enum_ConfigTypes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Protobuf_Enum_ConfigTypes_proto_goTypes = []any{
	(ConfigTypes)(0), // 0: ClassIsland.Shared.Protobuf.Enum.ConfigTypes
}
var file_Protobuf_Enum_ConfigTypes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_Enum_ConfigTypes_proto_init() }
func file_Protobuf_Enum_ConfigTypes_proto_init() {
	if File_Protobuf_Enum_ConfigTypes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Enum_ConfigTypes_proto_rawDesc), len(file_Protobuf_Enum_ConfigTypes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_Enum_ConfigTypes_proto_goTypes,
		DependencyIndexes: file_Protobuf_Enum_ConfigTypes_proto_depIdxs,
		EnumInfos:         file_Protobuf_Enum_ConfigTypes_proto_enumTypes,
	}.Build()
	File_Protobuf_Enum_ConfigTypes_proto = out.File
	file_Protobuf_Enum_ConfigTypes_proto_goTypes = nil
	file_Protobuf_Enum_ConfigTypes_proto_depIdxs = nil
}
