// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Enum/ListItemUpdateOperations.proto

package Enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListItemUpdateOperations int32

const (
	ListItemUpdateOperations_ListItemUpdateOperationsUnspecified ListItemUpdateOperations = 0
	ListItemUpdateOperations_Add                                 ListItemUpdateOperations = 1
	ListItemUpdateOperations_Update                              ListItemUpdateOperations = 2
	ListItemUpdateOperations_Remove                              ListItemUpdateOperations = 3
)

// Enum value maps for ListItemUpdateOperations.
var (
	ListItemUpdateOperations_name = map[int32]string{
		0: "ListItemUpdateOperationsUnspecified",
		1: "Add",
		2: "Update",
		3: "Remove",
	}
	ListItemUpdateOperations_value = map[string]int32{
		"ListItemUpdateOperationsUnspecified": 0,
		"Add":                                 1,
		"Update":                              2,
		"Remove":                              3,
	}
)

func (x ListItemUpdateOperations) Enum() *ListItemUpdateOperations {
	p := new(ListItemUpdateOperations)
	*p = x
	return p
}

func (x ListItemUpdateOperations) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListItemUpdateOperations) Descriptor() protoreflect.EnumDescriptor {
	return file_Protobuf_Enum_ListItemUpdateOperations_proto_enumTypes[0].Descriptor()
}

func (ListItemUpdateOperations) Type() protoreflect.EnumType {
	return &file_Protobuf_Enum_ListItemUpdateOperations_proto_enumTypes[0]
}

func (x ListItemUpdateOperations) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListItemUpdateOperations.Descriptor instead.
func (ListItemUpdateOperations) EnumDescriptor() ([]byte, []int) {
	return file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDescGZIP(), []int{0}
}

var File_Protobuf_Enum_ListItemUpdateOperations_proto protoreflect.FileDescriptor

const file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDesc = "" +
	"\n" +
	",Protobuf/Enum/ListItemUpdateOperations.proto\x12 ClassIsland.Shared.Protobuf.Enum*d\n" +
	"\x18ListItemUpdateOperations\x12'\n" +
	"#ListItemUpdateOperationsUnspecified\x10\x00\x12\a\n" +
	"\x03Add\x10\x01\x12\n" +
	"\n" +
	"\x06Update\x10\x02\x12\n" +
	"\n" +
	"\x06Remove\x10\x03B#\xaa\x02 ClassIsland.Shared.Protobuf.Enumb\x06proto3"

var (
	file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDescOnce sync.Once
	file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDescData []byte
)

func file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDescGZIP() []byte {
	file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDescOnce.Do(func() {
		file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDesc), len(file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDesc)))
	})
	return file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDescData
}

var file_Protobuf_Enum_ListItemUpdateOperations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Protobuf_Enum_ListItemUpdateOperations_proto_goTypes = []any{
	(ListItemUpdateOperations)(0), // 0: ClassIsland.Shared.Protobuf.Enum.ListItemUpdateOperations
}
var file_Protobuf_Enum_ListItemUpdateOperations_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_Enum_ListItemUpdateOperations_proto_init() }
func file_Protobuf_Enum_ListItemUpdateOperations_proto_init() {
	if File_Protobuf_Enum_ListItemUpdateOperations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDesc), len(file_Protobuf_Enum_ListItemUpdateOperations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_Enum_ListItemUpdateOperations_proto_goTypes,
		DependencyIndexes: file_Protobuf_Enum_ListItemUpdateOperations_proto_depIdxs,
		EnumInfos:         file_Protobuf_Enum_ListItemUpdateOperations_proto_enumTypes,
	}.Build()
	File_Protobuf_Enum_ListItemUpdateOperations_proto = out.File
	file_Protobuf_Enum_ListItemUpdateOperations_proto_goTypes = nil
	file_Protobuf_Enum_ListItemUpdateOperations_proto_depIdxs = nil
}
