// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Enum/Retcode.proto

package Enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Retcode int32

const (
	Retcode_Unspecified         Retcode = 0 // None = 0;
	Retcode_Success             Retcode = 200
	Retcode_ServerInternalError Retcode = 500
	Retcode_InvalidRequest      Retcode = 404
	// protocol: Handshake
	Retcode_HandshakeClientRejected Retcode = 1001
	// service: ClientRegister
	Retcode_Registered     Retcode = 10001
	Retcode_ClientNotFound Retcode = 10002 // service: ClientCommandDeliver
)

// Enum value maps for Retcode.
var (
	Retcode_name = map[int32]string{
		0:     "Unspecified",
		200:   "Success",
		500:   "ServerInternalError",
		404:   "InvalidRequest",
		1001:  "HandshakeClientRejected",
		10001: "Registered",
		10002: "ClientNotFound",
	}
	Retcode_value = map[string]int32{
		"Unspecified":             0,
		"Success":                 200,
		"ServerInternalError":     500,
		"InvalidRequest":          404,
		"HandshakeClientRejected": 1001,
		"Registered":              10001,
		"ClientNotFound":          10002,
	}
)

func (x Retcode) Enum() *Retcode {
	p := new(Retcode)
	*p = x
	return p
}

func (x Retcode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Retcode) Descriptor() protoreflect.EnumDescriptor {
	return file_Protobuf_Enum_Retcode_proto_enumTypes[0].Descriptor()
}

func (Retcode) Type() protoreflect.EnumType {
	return &file_Protobuf_Enum_Retcode_proto_enumTypes[0]
}

func (x Retcode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Retcode.Descriptor instead.
func (Retcode) EnumDescriptor() ([]byte, []int) {
	return file_Protobuf_Enum_Retcode_proto_rawDescGZIP(), []int{0}
}

var File_Protobuf_Enum_Retcode_proto protoreflect.FileDescriptor

const file_Protobuf_Enum_Retcode_proto_rawDesc = "" +
	"\n" +
	"\x1bProtobuf/Enum/Retcode.proto\x12 ClassIsland.Shared.Protobuf.Enum*\x9b\x01\n" +
	"\aRetcode\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\f\n" +
	"\aSuccess\x10\xc8\x01\x12\x18\n" +
	"\x13ServerInternalError\x10\xf4\x03\x12\x13\n" +
	"\x0eInvalidRequest\x10\x94\x03\x12\x1c\n" +
	"\x17HandshakeClientRejected\x10\xe9\a\x12\x0f\n" +
	"\n" +
	"Registered\x10\x91N\x12\x13\n" +
	"\x0eClientNotFound\x10\x92NB#\xaa\x02 ClassIsland.Shared.Protobuf.Enumb\x06proto3"

var (
	file_Protobuf_Enum_Retcode_proto_rawDescOnce sync.Once
	file_Protobuf_Enum_Retcode_proto_rawDescData []byte
)

func file_Protobuf_Enum_Retcode_proto_rawDescGZIP() []byte {
	file_Protobuf_Enum_Retcode_proto_rawDescOnce.Do(func() {
		file_Protobuf_Enum_Retcode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_Enum_Retcode_proto_rawDesc), len(file_Protobuf_Enum_Retcode_proto_rawDesc)))
	})
	return file_Protobuf_Enum_Retcode_proto_rawDescData
}

var file_Protobuf_Enum_Retcode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Protobuf_Enum_Retcode_proto_goTypes = []any{
	(Retcode)(0), // 0: ClassIsland.Shared.Protobuf.Enum.Retcode
}
var file_Protobuf_Enum_Retcode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_Enum_Retcode_proto_init() }
func file_Protobuf_Enum_Retcode_proto_init() {
	if File_Protobuf_Enum_Retcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Enum_Retcode_proto_rawDesc), len(file_Protobuf_Enum_Retcode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_Enum_Retcode_proto_goTypes,
		DependencyIndexes: file_Protobuf_Enum_Retcode_proto_depIdxs,
		EnumInfos:         file_Protobuf_Enum_Retcode_proto_enumTypes,
	}.Build()
	File_Protobuf_Enum_Retcode_proto = out.File
	file_Protobuf_Enum_Retcode_proto_goTypes = nil
	file_Protobuf_Enum_Retcode_proto_depIdxs = nil
}
