from Protobuf.Server import ClientCommandDeliverScRsp_pb2 as _ClientCommandDeliverScRsp_pb2
from Protobuf.Client import ClientCommandDeliverScReq_pb2 as _ClientCommandDeliverScReq_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
