// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Command/GetClientConfig.proto

package Command

import (
	Enum "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Enum"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetClientConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestGuid   string                 `protobuf:"bytes,1,opt,name=RequestGuid,proto3" json:"RequestGuid,omitempty"`
	ConfigType    Enum.ConfigTypes       `protobuf:"varint,2,opt,name=ConfigType,proto3,enum=ClassIsland.Shared.Protobuf.Enum.ConfigTypes" json:"ConfigType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientConfig) Reset() {
	*x = GetClientConfig{}
	mi := &file_Protobuf_Command_GetClientConfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientConfig) ProtoMessage() {}

func (x *GetClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_Command_GetClientConfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientConfig.ProtoReflect.Descriptor instead.
func (*GetClientConfig) Descriptor() ([]byte, []int) {
	return file_Protobuf_Command_GetClientConfig_proto_rawDescGZIP(), []int{0}
}

func (x *GetClientConfig) GetRequestGuid() string {
	if x != nil {
		return x.RequestGuid
	}
	return ""
}

func (x *GetClientConfig) GetConfigType() Enum.ConfigTypes {
	if x != nil {
		return x.ConfigType
	}
	return Enum.ConfigTypes(0)
}

var File_Protobuf_Command_GetClientConfig_proto protoreflect.FileDescriptor

const file_Protobuf_Command_GetClientConfig_proto_rawDesc = "" +
	"\n" +
	"&Protobuf/Command/GetClientConfig.proto\x12#ClassIsland.Shared.Protobuf.Command\x1a\x1fProtobuf/Enum/ConfigTypes.proto\"\x82\x01\n" +
	"\x0fGetClientConfig\x12 \n" +
	"\vRequestGuid\x18\x01 \x01(\tR\vRequestGuid\x12M\n" +
	"\n" +
	"ConfigType\x18\x02 \x01(\x0e2-.ClassIsland.Shared.Protobuf.Enum.ConfigTypesR\n" +
	"ConfigTypeB&\xaa\x02#ClassIsland.Shared.Protobuf.Commandb\x06proto3"

var (
	file_Protobuf_Command_GetClientConfig_proto_rawDescOnce sync.Once
	file_Protobuf_Command_GetClientConfig_proto_rawDescData []byte
)

func file_Protobuf_Command_GetClientConfig_proto_rawDescGZIP() []byte {
	file_Protobuf_Command_GetClientConfig_proto_rawDescOnce.Do(func() {
		file_Protobuf_Command_GetClientConfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_Command_GetClientConfig_proto_rawDesc), len(file_Protobuf_Command_GetClientConfig_proto_rawDesc)))
	})
	return file_Protobuf_Command_GetClientConfig_proto_rawDescData
}

var file_Protobuf_Command_GetClientConfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Protobuf_Command_GetClientConfig_proto_goTypes = []any{
	(*GetClientConfig)(nil), // 0: ClassIsland.Shared.Protobuf.Command.GetClientConfig
	(Enum.ConfigTypes)(0),   // 1: ClassIsland.Shared.Protobuf.Enum.ConfigTypes
}
var file_Protobuf_Command_GetClientConfig_proto_depIdxs = []int32{
	1, // 0: ClassIsland.Shared.Protobuf.Command.GetClientConfig.ConfigType:type_name -> ClassIsland.Shared.Protobuf.Enum.ConfigTypes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Protobuf_Command_GetClientConfig_proto_init() }
func file_Protobuf_Command_GetClientConfig_proto_init() {
	if File_Protobuf_Command_GetClientConfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Command_GetClientConfig_proto_rawDesc), len(file_Protobuf_Command_GetClientConfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_Command_GetClientConfig_proto_goTypes,
		DependencyIndexes: file_Protobuf_Command_GetClientConfig_proto_depIdxs,
		MessageInfos:      file_Protobuf_Command_GetClientConfig_proto_msgTypes,
	}.Build()
	File_Protobuf_Command_GetClientConfig_proto = out.File
	file_Protobuf_Command_GetClientConfig_proto_goTypes = nil
	file_Protobuf_Command_GetClientConfig_proto_depIdxs = nil
}
