// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Command/SendNotification.proto

package Command

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendNotification struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageMask      string                 `protobuf:"bytes,1,opt,name=MessageMask,proto3" json:"MessageMask,omitempty"`
	MessageContent   string                 `protobuf:"bytes,2,opt,name=MessageContent,proto3" json:"MessageContent,omitempty"`
	OverlayIconLeft  int32                  `protobuf:"varint,3,opt,name=OverlayIconLeft,proto3" json:"OverlayIconLeft,omitempty"`
	OverlayIconRight int32                  `protobuf:"varint,4,opt,name=OverlayIconRight,proto3" json:"OverlayIconRight,omitempty"`
	IsEmergency      bool                   `protobuf:"varint,5,opt,name=IsEmergency,proto3" json:"IsEmergency,omitempty"`
	// 提醒设置
	IsSpeechEnabled bool `protobuf:"varint,6,opt,name=IsSpeechEnabled,proto3" json:"IsSpeechEnabled,omitempty"`
	IsEffectEnabled bool `protobuf:"varint,7,opt,name=IsEffectEnabled,proto3" json:"IsEffectEnabled,omitempty"`
	IsSoundEnabled  bool `protobuf:"varint,8,opt,name=IsSoundEnabled,proto3" json:"IsSoundEnabled,omitempty"`
	IsTopmost       bool `protobuf:"varint,9,opt,name=IsTopmost,proto3" json:"IsTopmost,omitempty"`
	// 显示设置
	DurationSeconds float64 `protobuf:"fixed64,10,opt,name=DurationSeconds,proto3" json:"DurationSeconds,omitempty"` // 单次显示持续时间
	RepeatCounts    int32   `protobuf:"varint,11,opt,name=RepeatCounts,proto3" json:"RepeatCounts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendNotification) Reset() {
	*x = SendNotification{}
	mi := &file_Protobuf_Command_SendNotification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotification) ProtoMessage() {}

func (x *SendNotification) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_Command_SendNotification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotification.ProtoReflect.Descriptor instead.
func (*SendNotification) Descriptor() ([]byte, []int) {
	return file_Protobuf_Command_SendNotification_proto_rawDescGZIP(), []int{0}
}

func (x *SendNotification) GetMessageMask() string {
	if x != nil {
		return x.MessageMask
	}
	return ""
}

func (x *SendNotification) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *SendNotification) GetOverlayIconLeft() int32 {
	if x != nil {
		return x.OverlayIconLeft
	}
	return 0
}

func (x *SendNotification) GetOverlayIconRight() int32 {
	if x != nil {
		return x.OverlayIconRight
	}
	return 0
}

func (x *SendNotification) GetIsEmergency() bool {
	if x != nil {
		return x.IsEmergency
	}
	return false
}

func (x *SendNotification) GetIsSpeechEnabled() bool {
	if x != nil {
		return x.IsSpeechEnabled
	}
	return false
}

func (x *SendNotification) GetIsEffectEnabled() bool {
	if x != nil {
		return x.IsEffectEnabled
	}
	return false
}

func (x *SendNotification) GetIsSoundEnabled() bool {
	if x != nil {
		return x.IsSoundEnabled
	}
	return false
}

func (x *SendNotification) GetIsTopmost() bool {
	if x != nil {
		return x.IsTopmost
	}
	return false
}

func (x *SendNotification) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *SendNotification) GetRepeatCounts() int32 {
	if x != nil {
		return x.RepeatCounts
	}
	return 0
}

var File_Protobuf_Command_SendNotification_proto protoreflect.FileDescriptor

const file_Protobuf_Command_SendNotification_proto_rawDesc = "" +
	"\n" +
	"'Protobuf/Command/SendNotification.proto\x12#ClassIsland.Shared.Protobuf.Command\"\xbc\x03\n" +
	"\x10SendNotification\x12 \n" +
	"\vMessageMask\x18\x01 \x01(\tR\vMessageMask\x12&\n" +
	"\x0eMessageContent\x18\x02 \x01(\tR\x0eMessageContent\x12(\n" +
	"\x0fOverlayIconLeft\x18\x03 \x01(\x05R\x0fOverlayIconLeft\x12*\n" +
	"\x10OverlayIconRight\x18\x04 \x01(\x05R\x10OverlayIconRight\x12 \n" +
	"\vIsEmergency\x18\x05 \x01(\bR\vIsEmergency\x12(\n" +
	"\x0fIsSpeechEnabled\x18\x06 \x01(\bR\x0fIsSpeechEnabled\x12(\n" +
	"\x0fIsEffectEnabled\x18\a \x01(\bR\x0fIsEffectEnabled\x12&\n" +
	"\x0eIsSoundEnabled\x18\b \x01(\bR\x0eIsSoundEnabled\x12\x1c\n" +
	"\tIsTopmost\x18\t \x01(\bR\tIsTopmost\x12(\n" +
	"\x0fDurationSeconds\x18\n" +
	" \x01(\x01R\x0fDurationSeconds\x12\"\n" +
	"\fRepeatCounts\x18\v \x01(\x05R\fRepeatCountsB&\xaa\x02#ClassIsland.Shared.Protobuf.Commandb\x06proto3"

var (
	file_Protobuf_Command_SendNotification_proto_rawDescOnce sync.Once
	file_Protobuf_Command_SendNotification_proto_rawDescData []byte
)

func file_Protobuf_Command_SendNotification_proto_rawDescGZIP() []byte {
	file_Protobuf_Command_SendNotification_proto_rawDescOnce.Do(func() {
		file_Protobuf_Command_SendNotification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_Command_SendNotification_proto_rawDesc), len(file_Protobuf_Command_SendNotification_proto_rawDesc)))
	})
	return file_Protobuf_Command_SendNotification_proto_rawDescData
}

var file_Protobuf_Command_SendNotification_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Protobuf_Command_SendNotification_proto_goTypes = []any{
	(*SendNotification)(nil), // 0: ClassIsland.Shared.Protobuf.Command.SendNotification
}
var file_Protobuf_Command_SendNotification_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_Command_SendNotification_proto_init() }
func file_Protobuf_Command_SendNotification_proto_init() {
	if File_Protobuf_Command_SendNotification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Command_SendNotification_proto_rawDesc), len(file_Protobuf_Command_SendNotification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_Command_SendNotification_proto_goTypes,
		DependencyIndexes: file_Protobuf_Command_SendNotification_proto_depIdxs,
		MessageInfos:      file_Protobuf_Command_SendNotification_proto_msgTypes,
	}.Build()
	File_Protobuf_Command_SendNotification_proto = out.File
	file_Protobuf_Command_SendNotification_proto_goTypes = nil
	file_Protobuf_Command_SendNotification_proto_depIdxs = nil
}
