// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Service/Audit.proto

package Service

import (
	Client "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Client"
	Server "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Server"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_Protobuf_Service_Audit_proto protoreflect.FileDescriptor

const file_Protobuf_Service_Audit_proto_rawDesc = "" +
	"\n" +
	"\x1cProtobuf/Service/Audit.proto\x12#ClassIsland.Shared.Protobuf.Service\x1a Protobuf/Client/AuditScReq.proto\x1a Protobuf/Server/AuditScRsp.proto2s\n" +
	"\x05Audit\x12j\n" +
	"\bLogEvent\x12..ClassIsland.Shared.Protobuf.Client.AuditScReq\x1a..ClassIsland.Shared.Protobuf.Server.AuditScRspB&\xaa\x02#ClassIsland.Shared.Protobuf.Serviceb\x06proto3"

var file_Protobuf_Service_Audit_proto_goTypes = []any{
	(*Client.AuditScReq)(nil), // 0: ClassIsland.Shared.Protobuf.Client.AuditScReq
	(*Server.AuditScRsp)(nil), // 1: ClassIsland.Shared.Protobuf.Server.AuditScRsp
}
var file_Protobuf_Service_Audit_proto_depIdxs = []int32{
	0, // 0: ClassIsland.Shared.Protobuf.Service.Audit.LogEvent:input_type -> ClassIsland.Shared.Protobuf.Client.AuditScReq
	1, // 1: ClassIsland.Shared.Protobuf.Service.Audit.LogEvent:output_type -> ClassIsland.Shared.Protobuf.Server.AuditScRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_Service_Audit_proto_init() }
func file_Protobuf_Service_Audit_proto_init() {
	if File_Protobuf_Service_Audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Service_Audit_proto_rawDesc), len(file_Protobuf_Service_Audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Protobuf_Service_Audit_proto_goTypes,
		DependencyIndexes: file_Protobuf_Service_Audit_proto_depIdxs,
	}.Build()
	File_Protobuf_Service_Audit_proto = out.File
	file_Protobuf_Service_Audit_proto_goTypes = nil
	file_Protobuf_Service_Audit_proto_depIdxs = nil
}
