// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Service/ClientRegister.proto

package Service

import (
	Client "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Client"
	Server "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Server"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_Protobuf_Service_ClientRegister_proto protoreflect.FileDescriptor

const file_Protobuf_Service_ClientRegister_proto_rawDesc = "" +
	"\n" +
	"%Protobuf/Service/ClientRegister.proto\x12#ClassIsland.Shared.Protobuf.Service\x1a)Protobuf/Client/ClientRegisterCsReq.proto\x1a)Protobuf/Server/ClientRegisterScRsp.proto2\x8e\x02\n" +
	"\x0eClientRegister\x12|\n" +
	"\bRegister\x127.ClassIsland.Shared.Protobuf.Client.ClientRegisterCsReq\x1a7.ClassIsland.Shared.Protobuf.Server.ClientRegisterScRsp\x12~\n" +
	"\n" +
	"UnRegister\x127.ClassIsland.Shared.Protobuf.Client.ClientRegisterCsReq\x1a7.ClassIsland.Shared.Protobuf.Server.ClientRegisterScRspB&\xaa\x02#ClassIsland.Shared.Protobuf.Serviceb\x06proto3"

var file_Protobuf_Service_ClientRegister_proto_goTypes = []any{
	(*Client.ClientRegisterCsReq)(nil), // 0: ClassIsland.Shared.Protobuf.Client.ClientRegisterCsReq
	(*Server.ClientRegisterScRsp)(nil), // 1: ClassIsland.Shared.Protobuf.Server.ClientRegisterScRsp
}
var file_Protobuf_Service_ClientRegister_proto_depIdxs = []int32{
	0, // 0: ClassIsland.Shared.Protobuf.Service.ClientRegister.Register:input_type -> ClassIsland.Shared.Protobuf.Client.ClientRegisterCsReq
	0, // 1: ClassIsland.Shared.Protobuf.Service.ClientRegister.UnRegister:input_type -> ClassIsland.Shared.Protobuf.Client.ClientRegisterCsReq
	1, // 2: ClassIsland.Shared.Protobuf.Service.ClientRegister.Register:output_type -> ClassIsland.Shared.Protobuf.Server.ClientRegisterScRsp
	1, // 3: ClassIsland.Shared.Protobuf.Service.ClientRegister.UnRegister:output_type -> ClassIsland.Shared.Protobuf.Server.ClientRegisterScRsp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_Service_ClientRegister_proto_init() }
func file_Protobuf_Service_ClientRegister_proto_init() {
	if File_Protobuf_Service_ClientRegister_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Service_ClientRegister_proto_rawDesc), len(file_Protobuf_Service_ClientRegister_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Protobuf_Service_ClientRegister_proto_goTypes,
		DependencyIndexes: file_Protobuf_Service_ClientRegister_proto_depIdxs,
	}.Build()
	File_Protobuf_Service_ClientRegister_proto = out.File
	file_Protobuf_Service_ClientRegister_proto_goTypes = nil
	file_Protobuf_Service_ClientRegister_proto_depIdxs = nil
}
