// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: Protobuf/Service/ClientRegister.proto

package Service

import (
	context "context"
	Client "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Client"
	Server "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Server"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientRegister_Register_FullMethodName   = "/ClassIsland.Shared.Protobuf.Service.ClientRegister/Register"
	ClientRegister_UnRegister_FullMethodName = "/ClassIsland.Shared.Protobuf.Service.ClientRegister/UnRegister"
)

// ClientRegisterClient is the client API for ClientRegister service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientRegisterClient interface {
	Register(ctx context.Context, in *Client.ClientRegisterCsReq, opts ...grpc.CallOption) (*Server.ClientRegisterScRsp, error)
	UnRegister(ctx context.Context, in *Client.ClientRegisterCsReq, opts ...grpc.CallOption) (*Server.ClientRegisterScRsp, error)
}

type clientRegisterClient struct {
	cc grpc.ClientConnInterface
}

func NewClientRegisterClient(cc grpc.ClientConnInterface) ClientRegisterClient {
	return &clientRegisterClient{cc}
}

func (c *clientRegisterClient) Register(ctx context.Context, in *Client.ClientRegisterCsReq, opts ...grpc.CallOption) (*Server.ClientRegisterScRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Server.ClientRegisterScRsp)
	err := c.cc.Invoke(ctx, ClientRegister_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientRegisterClient) UnRegister(ctx context.Context, in *Client.ClientRegisterCsReq, opts ...grpc.CallOption) (*Server.ClientRegisterScRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Server.ClientRegisterScRsp)
	err := c.cc.Invoke(ctx, ClientRegister_UnRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientRegisterServer is the server API for ClientRegister service.
// All implementations must embed UnimplementedClientRegisterServer
// for forward compatibility.
type ClientRegisterServer interface {
	Register(context.Context, *Client.ClientRegisterCsReq) (*Server.ClientRegisterScRsp, error)
	UnRegister(context.Context, *Client.ClientRegisterCsReq) (*Server.ClientRegisterScRsp, error)
	mustEmbedUnimplementedClientRegisterServer()
}

// UnimplementedClientRegisterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientRegisterServer struct{}

func (UnimplementedClientRegisterServer) Register(context.Context, *Client.ClientRegisterCsReq) (*Server.ClientRegisterScRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedClientRegisterServer) UnRegister(context.Context, *Client.ClientRegisterCsReq) (*Server.ClientRegisterScRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnRegister not implemented")
}
func (UnimplementedClientRegisterServer) mustEmbedUnimplementedClientRegisterServer() {}
func (UnimplementedClientRegisterServer) testEmbeddedByValue()                        {}

// UnsafeClientRegisterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientRegisterServer will
// result in compilation errors.
type UnsafeClientRegisterServer interface {
	mustEmbedUnimplementedClientRegisterServer()
}

func RegisterClientRegisterServer(s grpc.ServiceRegistrar, srv ClientRegisterServer) {
	// If the following call panics, it indicates UnimplementedClientRegisterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientRegister_ServiceDesc, srv)
}

func _ClientRegister_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client.ClientRegisterCsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientRegisterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientRegister_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientRegisterServer).Register(ctx, req.(*Client.ClientRegisterCsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientRegister_UnRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client.ClientRegisterCsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientRegisterServer).UnRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientRegister_UnRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientRegisterServer).UnRegister(ctx, req.(*Client.ClientRegisterCsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientRegister_ServiceDesc is the grpc.ServiceDesc for ClientRegister service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientRegister_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClassIsland.Shared.Protobuf.Service.ClientRegister",
	HandlerType: (*ClientRegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ClientRegister_Register_Handler,
		},
		{
			MethodName: "UnRegister",
			Handler:    _ClientRegister_UnRegister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Protobuf/Service/ClientRegister.proto",
}
