// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: Protobuf/Service/ClientCommandDeliver.proto

package Service

import (
	context "context"
	Client "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Client"
	Server "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Server"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientCommandDeliver_ListenCommand_FullMethodName = "/ClassIsland.Shared.Protobuf.Service.ClientCommandDeliver/ListenCommand"
)

// ClientCommandDeliverClient is the client API for ClientCommandDeliver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientCommandDeliverClient interface {
	ListenCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Client.ClientCommandDeliverScReq, Server.ClientCommandDeliverScRsp], error)
}

type clientCommandDeliverClient struct {
	cc grpc.ClientConnInterface
}

func NewClientCommandDeliverClient(cc grpc.ClientConnInterface) ClientCommandDeliverClient {
	return &clientCommandDeliverClient{cc}
}

func (c *clientCommandDeliverClient) ListenCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Client.ClientCommandDeliverScReq, Server.ClientCommandDeliverScRsp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientCommandDeliver_ServiceDesc.Streams[0], ClientCommandDeliver_ListenCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Client.ClientCommandDeliverScReq, Server.ClientCommandDeliverScRsp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientCommandDeliver_ListenCommandClient = grpc.BidiStreamingClient[Client.ClientCommandDeliverScReq, Server.ClientCommandDeliverScRsp]

// ClientCommandDeliverServer is the server API for ClientCommandDeliver service.
// All implementations must embed UnimplementedClientCommandDeliverServer
// for forward compatibility.
type ClientCommandDeliverServer interface {
	ListenCommand(grpc.BidiStreamingServer[Client.ClientCommandDeliverScReq, Server.ClientCommandDeliverScRsp]) error
	mustEmbedUnimplementedClientCommandDeliverServer()
}

// UnimplementedClientCommandDeliverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientCommandDeliverServer struct{}

func (UnimplementedClientCommandDeliverServer) ListenCommand(grpc.BidiStreamingServer[Client.ClientCommandDeliverScReq, Server.ClientCommandDeliverScRsp]) error {
	return status.Error(codes.Unimplemented, "method ListenCommand not implemented")
}
func (UnimplementedClientCommandDeliverServer) mustEmbedUnimplementedClientCommandDeliverServer() {}
func (UnimplementedClientCommandDeliverServer) testEmbeddedByValue()                              {}

// UnsafeClientCommandDeliverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientCommandDeliverServer will
// result in compilation errors.
type UnsafeClientCommandDeliverServer interface {
	mustEmbedUnimplementedClientCommandDeliverServer()
}

func RegisterClientCommandDeliverServer(s grpc.ServiceRegistrar, srv ClientCommandDeliverServer) {
	// If the following call panics, it indicates UnimplementedClientCommandDeliverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientCommandDeliver_ServiceDesc, srv)
}

func _ClientCommandDeliver_ListenCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientCommandDeliverServer).ListenCommand(&grpc.GenericServerStream[Client.ClientCommandDeliverScReq, Server.ClientCommandDeliverScRsp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientCommandDeliver_ListenCommandServer = grpc.BidiStreamingServer[Client.ClientCommandDeliverScReq, Server.ClientCommandDeliverScRsp]

// ClientCommandDeliver_ServiceDesc is the grpc.ServiceDesc for ClientCommandDeliver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientCommandDeliver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClassIsland.Shared.Protobuf.Service.ClientCommandDeliver",
	HandlerType: (*ClientCommandDeliverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenCommand",
			Handler:       _ClientCommandDeliver_ListenCommand_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Protobuf/Service/ClientCommandDeliver.proto",
}
