// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: Protobuf/Service/ConfigUpload.proto

package Service

import (
	context "context"
	Client "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Client"
	Server "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Server"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigUpload_UploadConfig_FullMethodName = "/ClassIsland.Shared.Protobuf.Service.ConfigUpload/UploadConfig"
)

// ConfigUploadClient is the client API for ConfigUpload service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigUploadClient interface {
	UploadConfig(ctx context.Context, in *Client.ConfigUploadScReq, opts ...grpc.CallOption) (*Server.ConfigUploadScRsp, error)
}

type configUploadClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigUploadClient(cc grpc.ClientConnInterface) ConfigUploadClient {
	return &configUploadClient{cc}
}

func (c *configUploadClient) UploadConfig(ctx context.Context, in *Client.ConfigUploadScReq, opts ...grpc.CallOption) (*Server.ConfigUploadScRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Server.ConfigUploadScRsp)
	err := c.cc.Invoke(ctx, ConfigUpload_UploadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigUploadServer is the server API for ConfigUpload service.
// All implementations must embed UnimplementedConfigUploadServer
// for forward compatibility.
type ConfigUploadServer interface {
	UploadConfig(context.Context, *Client.ConfigUploadScReq) (*Server.ConfigUploadScRsp, error)
	mustEmbedUnimplementedConfigUploadServer()
}

// UnimplementedConfigUploadServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigUploadServer struct{}

func (UnimplementedConfigUploadServer) UploadConfig(context.Context, *Client.ConfigUploadScReq) (*Server.ConfigUploadScRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadConfig not implemented")
}
func (UnimplementedConfigUploadServer) mustEmbedUnimplementedConfigUploadServer() {}
func (UnimplementedConfigUploadServer) testEmbeddedByValue()                      {}

// UnsafeConfigUploadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigUploadServer will
// result in compilation errors.
type UnsafeConfigUploadServer interface {
	mustEmbedUnimplementedConfigUploadServer()
}

func RegisterConfigUploadServer(s grpc.ServiceRegistrar, srv ConfigUploadServer) {
	// If the following call panics, it indicates UnimplementedConfigUploadServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigUpload_ServiceDesc, srv)
}

func _ConfigUpload_UploadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client.ConfigUploadScReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigUploadServer).UploadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigUpload_UploadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigUploadServer).UploadConfig(ctx, req.(*Client.ConfigUploadScReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigUpload_ServiceDesc is the grpc.ServiceDesc for ConfigUpload service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigUpload_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClassIsland.Shared.Protobuf.Service.ConfigUpload",
	HandlerType: (*ConfigUploadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadConfig",
			Handler:    _ConfigUpload_UploadConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Protobuf/Service/ConfigUpload.proto",
}
