// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: Protobuf/Service/Handshake.proto

package Service

import (
	context "context"
	Client "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Client"
	Server "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Server"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Handshake_BeginHandshake_FullMethodName    = "/ClassIsland.Shared.Protobuf.Service.Handshake/BeginHandshake"
	Handshake_CompleteHandshake_FullMethodName = "/ClassIsland.Shared.Protobuf.Service.Handshake/CompleteHandshake"
)

// HandshakeClient is the client API for Handshake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandshakeClient interface {
	BeginHandshake(ctx context.Context, in *Client.HandshakeScBeginHandShakeReq, opts ...grpc.CallOption) (*Server.HandshakeScBeginHandShakeRsp, error)
	CompleteHandshake(ctx context.Context, in *Client.HandshakeScCompleteHandshakeReq, opts ...grpc.CallOption) (*Server.HandshakeScCompleteHandshakeRsp, error)
}

type handshakeClient struct {
	cc grpc.ClientConnInterface
}

func NewHandshakeClient(cc grpc.ClientConnInterface) HandshakeClient {
	return &handshakeClient{cc}
}

func (c *handshakeClient) BeginHandshake(ctx context.Context, in *Client.HandshakeScBeginHandShakeReq, opts ...grpc.CallOption) (*Server.HandshakeScBeginHandShakeRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Server.HandshakeScBeginHandShakeRsp)
	err := c.cc.Invoke(ctx, Handshake_BeginHandshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handshakeClient) CompleteHandshake(ctx context.Context, in *Client.HandshakeScCompleteHandshakeReq, opts ...grpc.CallOption) (*Server.HandshakeScCompleteHandshakeRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Server.HandshakeScCompleteHandshakeRsp)
	err := c.cc.Invoke(ctx, Handshake_CompleteHandshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandshakeServer is the server API for Handshake service.
// All implementations must embed UnimplementedHandshakeServer
// for forward compatibility.
type HandshakeServer interface {
	BeginHandshake(context.Context, *Client.HandshakeScBeginHandShakeReq) (*Server.HandshakeScBeginHandShakeRsp, error)
	CompleteHandshake(context.Context, *Client.HandshakeScCompleteHandshakeReq) (*Server.HandshakeScCompleteHandshakeRsp, error)
	mustEmbedUnimplementedHandshakeServer()
}

// UnimplementedHandshakeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandshakeServer struct{}

func (UnimplementedHandshakeServer) BeginHandshake(context.Context, *Client.HandshakeScBeginHandShakeReq) (*Server.HandshakeScBeginHandShakeRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginHandshake not implemented")
}
func (UnimplementedHandshakeServer) CompleteHandshake(context.Context, *Client.HandshakeScCompleteHandshakeReq) (*Server.HandshakeScCompleteHandshakeRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteHandshake not implemented")
}
func (UnimplementedHandshakeServer) mustEmbedUnimplementedHandshakeServer() {}
func (UnimplementedHandshakeServer) testEmbeddedByValue()                   {}

// UnsafeHandshakeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandshakeServer will
// result in compilation errors.
type UnsafeHandshakeServer interface {
	mustEmbedUnimplementedHandshakeServer()
}

func RegisterHandshakeServer(s grpc.ServiceRegistrar, srv HandshakeServer) {
	// If the following call panics, it indicates UnimplementedHandshakeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Handshake_ServiceDesc, srv)
}

func _Handshake_BeginHandshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client.HandshakeScBeginHandShakeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandshakeServer).BeginHandshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handshake_BeginHandshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandshakeServer).BeginHandshake(ctx, req.(*Client.HandshakeScBeginHandShakeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Handshake_CompleteHandshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Client.HandshakeScCompleteHandshakeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandshakeServer).CompleteHandshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Handshake_CompleteHandshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandshakeServer).CompleteHandshake(ctx, req.(*Client.HandshakeScCompleteHandshakeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Handshake_ServiceDesc is the grpc.ServiceDesc for Handshake service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Handshake_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClassIsland.Shared.Protobuf.Service.Handshake",
	HandlerType: (*HandshakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginHandshake",
			Handler:    _Handshake_BeginHandshake_Handler,
		},
		{
			MethodName: "CompleteHandshake",
			Handler:    _Handshake_CompleteHandshake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Protobuf/Service/Handshake.proto",
}
