// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/Server/ClientRegisterScRsp.proto

package Server

import (
	Enum "github.com/MINIOpenSource/CIMS-backend/internal/proto/Protobuf/Enum"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientRegisterScRsp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Retcode         Enum.Retcode           `protobuf:"varint,1,opt,name=Retcode,proto3,enum=ClassIsland.Shared.Protobuf.Enum.Retcode" json:"Retcode,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	ServerPublicKey string                 `protobuf:"bytes,3,opt,name=ServerPublicKey,proto3" json:"ServerPublicKey,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientRegisterScRsp) Reset() {
	*x = ClientRegisterScRsp{}
	mi := &file_Protobuf_Server_ClientRegisterScRsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRegisterScRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegisterScRsp) ProtoMessage() {}

func (x *ClientRegisterScRsp) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_Server_ClientRegisterScRsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegisterScRsp.ProtoReflect.Descriptor instead.
func (*ClientRegisterScRsp) Descriptor() ([]byte, []int) {
	return file_Protobuf_Server_ClientRegisterScRsp_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRegisterScRsp) GetRetcode() Enum.Retcode {
	if x != nil {
		return x.Retcode
	}
	return Enum.Retcode(0)
}

func (x *ClientRegisterScRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClientRegisterScRsp) GetServerPublicKey() string {
	if x != nil {
		return x.ServerPublicKey
	}
	return ""
}

var File_Protobuf_Server_ClientRegisterScRsp_proto protoreflect.FileDescriptor

const file_Protobuf_Server_ClientRegisterScRsp_proto_rawDesc = "" +
	"\n" +
	")Protobuf/Server/ClientRegisterScRsp.proto\x12\"ClassIsland.Shared.Protobuf.Server\x1a\x1bProtobuf/Enum/Retcode.proto\"\x9e\x01\n" +
	"\x13ClientRegisterScRsp\x12C\n" +
	"\aRetcode\x18\x01 \x01(\x0e2).ClassIsland.Shared.Protobuf.Enum.RetcodeR\aRetcode\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12(\n" +
	"\x0fServerPublicKey\x18\x03 \x01(\tR\x0fServerPublicKeyB%\xaa\x02\"ClassIsland.Shared.Protobuf.Serverb\x06proto3"

var (
	file_Protobuf_Server_ClientRegisterScRsp_proto_rawDescOnce sync.Once
	file_Protobuf_Server_ClientRegisterScRsp_proto_rawDescData []byte
)

func file_Protobuf_Server_ClientRegisterScRsp_proto_rawDescGZIP() []byte {
	file_Protobuf_Server_ClientRegisterScRsp_proto_rawDescOnce.Do(func() {
		file_Protobuf_Server_ClientRegisterScRsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_Server_ClientRegisterScRsp_proto_rawDesc), len(file_Protobuf_Server_ClientRegisterScRsp_proto_rawDesc)))
	})
	return file_Protobuf_Server_ClientRegisterScRsp_proto_rawDescData
}

var file_Protobuf_Server_ClientRegisterScRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Protobuf_Server_ClientRegisterScRsp_proto_goTypes = []any{
	(*ClientRegisterScRsp)(nil), // 0: ClassIsland.Shared.Protobuf.Server.ClientRegisterScRsp
	(Enum.Retcode)(0),           // 1: ClassIsland.Shared.Protobuf.Enum.Retcode
}
var file_Protobuf_Server_ClientRegisterScRsp_proto_depIdxs = []int32{
	1, // 0: ClassIsland.Shared.Protobuf.Server.ClientRegisterScRsp.Retcode:type_name -> ClassIsland.Shared.Protobuf.Enum.Retcode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Protobuf_Server_ClientRegisterScRsp_proto_init() }
func file_Protobuf_Server_ClientRegisterScRsp_proto_init() {
	if File_Protobuf_Server_ClientRegisterScRsp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_Server_ClientRegisterScRsp_proto_rawDesc), len(file_Protobuf_Server_ClientRegisterScRsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_Server_ClientRegisterScRsp_proto_goTypes,
		DependencyIndexes: file_Protobuf_Server_ClientRegisterScRsp_proto_depIdxs,
		MessageInfos:      file_Protobuf_Server_ClientRegisterScRsp_proto_msgTypes,
	}.Build()
	File_Protobuf_Server_ClientRegisterScRsp_proto = out.File
	file_Protobuf_Server_ClientRegisterScRsp_proto_goTypes = nil
	file_Protobuf_Server_ClientRegisterScRsp_proto_depIdxs = nil
}
