// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/AuditEvent/AppSettingsUpdated.proto

package AuditEvent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppSettingsUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyName  string                 `protobuf:"bytes,1,opt,name=PropertyName,proto3" json:"PropertyName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppSettingsUpdated) Reset() {
	*x = AppSettingsUpdated{}
	mi := &file_Protobuf_AuditEvent_AppSettingsUpdated_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSettingsUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSettingsUpdated) ProtoMessage() {}

func (x *AppSettingsUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_AuditEvent_AppSettingsUpdated_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSettingsUpdated.ProtoReflect.Descriptor instead.
func (*AppSettingsUpdated) Descriptor() ([]byte, []int) {
	return file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDescGZIP(), []int{0}
}

func (x *AppSettingsUpdated) GetPropertyName() string {
	if x != nil {
		return x.PropertyName
	}
	return ""
}

var File_Protobuf_AuditEvent_AppSettingsUpdated_proto protoreflect.FileDescriptor

const file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDesc = "" +
	"\n" +
	",Protobuf/AuditEvent/AppSettingsUpdated.proto\x12&ClassIsland.Shared.Protobuf.AuditEvent\"8\n" +
	"\x12AppSettingsUpdated\x12\"\n" +
	"\fPropertyName\x18\x01 \x01(\tR\fPropertyNameB)\xaa\x02&ClassIsland.Shared.Protobuf.AuditEventb\x06proto3"

var (
	file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDescOnce sync.Once
	file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDescData []byte
)

func file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDescGZIP() []byte {
	file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDescOnce.Do(func() {
		file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDesc), len(file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDesc)))
	})
	return file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDescData
}

var file_Protobuf_AuditEvent_AppSettingsUpdated_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Protobuf_AuditEvent_AppSettingsUpdated_proto_goTypes = []any{
	(*AppSettingsUpdated)(nil), // 0: ClassIsland.Shared.Protobuf.AuditEvent.AppSettingsUpdated
}
var file_Protobuf_AuditEvent_AppSettingsUpdated_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_AuditEvent_AppSettingsUpdated_proto_init() }
func file_Protobuf_AuditEvent_AppSettingsUpdated_proto_init() {
	if File_Protobuf_AuditEvent_AppSettingsUpdated_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDesc), len(file_Protobuf_AuditEvent_AppSettingsUpdated_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_AuditEvent_AppSettingsUpdated_proto_goTypes,
		DependencyIndexes: file_Protobuf_AuditEvent_AppSettingsUpdated_proto_depIdxs,
		MessageInfos:      file_Protobuf_AuditEvent_AppSettingsUpdated_proto_msgTypes,
	}.Build()
	File_Protobuf_AuditEvent_AppSettingsUpdated_proto = out.File
	file_Protobuf_AuditEvent_AppSettingsUpdated_proto_goTypes = nil
	file_Protobuf_AuditEvent_AppSettingsUpdated_proto_depIdxs = nil
}
