// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/AuditEvent/ClassChangeCompleted.proto

package AuditEvent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassChangeCompleted struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ClassPlanId            string                 `protobuf:"bytes,1,opt,name=ClassPlanId,proto3" json:"ClassPlanId,omitempty"`
	ChangeMode             int32                  `protobuf:"varint,2,opt,name=ChangeMode,proto3" json:"ChangeMode,omitempty"`
	SourceClassIndex       int32                  `protobuf:"varint,3,opt,name=SourceClassIndex,proto3" json:"SourceClassIndex,omitempty"`
	SourceClassSubjectId   string                 `protobuf:"bytes,4,opt,name=SourceClassSubjectId,proto3" json:"SourceClassSubjectId,omitempty"`
	TargetClassIndex       int32                  `protobuf:"varint,5,opt,name=TargetClassIndex,proto3" json:"TargetClassIndex,omitempty"`
	TargetClassSubjectId   string                 `protobuf:"bytes,6,opt,name=TargetClassSubjectId,proto3" json:"TargetClassSubjectId,omitempty"`
	WriteToSourceClassPlan bool                   `protobuf:"varint,7,opt,name=WriteToSourceClassPlan,proto3" json:"WriteToSourceClassPlan,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ClassChangeCompleted) Reset() {
	*x = ClassChangeCompleted{}
	mi := &file_Protobuf_AuditEvent_ClassChangeCompleted_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassChangeCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassChangeCompleted) ProtoMessage() {}

func (x *ClassChangeCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_AuditEvent_ClassChangeCompleted_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassChangeCompleted.ProtoReflect.Descriptor instead.
func (*ClassChangeCompleted) Descriptor() ([]byte, []int) {
	return file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDescGZIP(), []int{0}
}

func (x *ClassChangeCompleted) GetClassPlanId() string {
	if x != nil {
		return x.ClassPlanId
	}
	return ""
}

func (x *ClassChangeCompleted) GetChangeMode() int32 {
	if x != nil {
		return x.ChangeMode
	}
	return 0
}

func (x *ClassChangeCompleted) GetSourceClassIndex() int32 {
	if x != nil {
		return x.SourceClassIndex
	}
	return 0
}

func (x *ClassChangeCompleted) GetSourceClassSubjectId() string {
	if x != nil {
		return x.SourceClassSubjectId
	}
	return ""
}

func (x *ClassChangeCompleted) GetTargetClassIndex() int32 {
	if x != nil {
		return x.TargetClassIndex
	}
	return 0
}

func (x *ClassChangeCompleted) GetTargetClassSubjectId() string {
	if x != nil {
		return x.TargetClassSubjectId
	}
	return ""
}

func (x *ClassChangeCompleted) GetWriteToSourceClassPlan() bool {
	if x != nil {
		return x.WriteToSourceClassPlan
	}
	return false
}

var File_Protobuf_AuditEvent_ClassChangeCompleted_proto protoreflect.FileDescriptor

const file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDesc = "" +
	"\n" +
	".Protobuf/AuditEvent/ClassChangeCompleted.proto\x12&ClassIsland.Shared.Protobuf.AuditEvent\"\xd0\x02\n" +
	"\x14ClassChangeCompleted\x12 \n" +
	"\vClassPlanId\x18\x01 \x01(\tR\vClassPlanId\x12\x1e\n" +
	"\n" +
	"ChangeMode\x18\x02 \x01(\x05R\n" +
	"ChangeMode\x12*\n" +
	"\x10SourceClassIndex\x18\x03 \x01(\x05R\x10SourceClassIndex\x122\n" +
	"\x14SourceClassSubjectId\x18\x04 \x01(\tR\x14SourceClassSubjectId\x12*\n" +
	"\x10TargetClassIndex\x18\x05 \x01(\x05R\x10TargetClassIndex\x122\n" +
	"\x14TargetClassSubjectId\x18\x06 \x01(\tR\x14TargetClassSubjectId\x126\n" +
	"\x16WriteToSourceClassPlan\x18\a \x01(\bR\x16WriteToSourceClassPlanB)\xaa\x02&ClassIsland.Shared.Protobuf.AuditEventb\x06proto3"

var (
	file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDescOnce sync.Once
	file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDescData []byte
)

func file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDescGZIP() []byte {
	file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDescOnce.Do(func() {
		file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDesc), len(file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDesc)))
	})
	return file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDescData
}

var file_Protobuf_AuditEvent_ClassChangeCompleted_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Protobuf_AuditEvent_ClassChangeCompleted_proto_goTypes = []any{
	(*ClassChangeCompleted)(nil), // 0: ClassIsland.Shared.Protobuf.AuditEvent.ClassChangeCompleted
}
var file_Protobuf_AuditEvent_ClassChangeCompleted_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_AuditEvent_ClassChangeCompleted_proto_init() }
func file_Protobuf_AuditEvent_ClassChangeCompleted_proto_init() {
	if File_Protobuf_AuditEvent_ClassChangeCompleted_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDesc), len(file_Protobuf_AuditEvent_ClassChangeCompleted_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_AuditEvent_ClassChangeCompleted_proto_goTypes,
		DependencyIndexes: file_Protobuf_AuditEvent_ClassChangeCompleted_proto_depIdxs,
		MessageInfos:      file_Protobuf_AuditEvent_ClassChangeCompleted_proto_msgTypes,
	}.Build()
	File_Protobuf_AuditEvent_ClassChangeCompleted_proto = out.File
	file_Protobuf_AuditEvent_ClassChangeCompleted_proto_goTypes = nil
	file_Protobuf_AuditEvent_ClassChangeCompleted_proto_depIdxs = nil
}
