// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: Protobuf/AuditEvent/PluginUninstalled.proto

package AuditEvent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginUninstalled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=PluginId,proto3" json:"PluginId,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginUninstalled) Reset() {
	*x = PluginUninstalled{}
	mi := &file_Protobuf_AuditEvent_PluginUninstalled_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginUninstalled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginUninstalled) ProtoMessage() {}

func (x *PluginUninstalled) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_AuditEvent_PluginUninstalled_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginUninstalled.ProtoReflect.Descriptor instead.
func (*PluginUninstalled) Descriptor() ([]byte, []int) {
	return file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDescGZIP(), []int{0}
}

func (x *PluginUninstalled) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginUninstalled) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_Protobuf_AuditEvent_PluginUninstalled_proto protoreflect.FileDescriptor

const file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDesc = "" +
	"\n" +
	"+Protobuf/AuditEvent/PluginUninstalled.proto\x12&ClassIsland.Shared.Protobuf.AuditEvent\"I\n" +
	"\x11PluginUninstalled\x12\x1a\n" +
	"\bPluginId\x18\x01 \x01(\tR\bPluginId\x12\x18\n" +
	"\aVersion\x18\x02 \x01(\tR\aVersionB)\xaa\x02&ClassIsland.Shared.Protobuf.AuditEventb\x06proto3"

var (
	file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDescOnce sync.Once
	file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDescData []byte
)

func file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDescGZIP() []byte {
	file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDescOnce.Do(func() {
		file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDesc), len(file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDesc)))
	})
	return file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDescData
}

var file_Protobuf_AuditEvent_PluginUninstalled_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Protobuf_AuditEvent_PluginUninstalled_proto_goTypes = []any{
	(*PluginUninstalled)(nil), // 0: ClassIsland.Shared.Protobuf.AuditEvent.PluginUninstalled
}
var file_Protobuf_AuditEvent_PluginUninstalled_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Protobuf_AuditEvent_PluginUninstalled_proto_init() }
func file_Protobuf_AuditEvent_PluginUninstalled_proto_init() {
	if File_Protobuf_AuditEvent_PluginUninstalled_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDesc), len(file_Protobuf_AuditEvent_PluginUninstalled_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Protobuf_AuditEvent_PluginUninstalled_proto_goTypes,
		DependencyIndexes: file_Protobuf_AuditEvent_PluginUninstalled_proto_depIdxs,
		MessageInfos:      file_Protobuf_AuditEvent_PluginUninstalled_proto_msgTypes,
	}.Build()
	File_Protobuf_AuditEvent_PluginUninstalled_proto = out.File
	file_Protobuf_AuditEvent_PluginUninstalled_proto_goTypes = nil
	file_Protobuf_AuditEvent_PluginUninstalled_proto_depIdxs = nil
}
