name: Build and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Run ruff
        run: ruff check .

      - name: Run black
        run: black --check .

  build:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: pip install -e .

      - name: Build protobuf (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: cims
        run: |
          $workDir = (Get-Location).Path + "\"
          $protoFiles = Get-ChildItem Protobuf -Recurse -Filter *.proto | ForEach-Object { $_.FullName.Replace($workDir, "") }
          python -m grpc_tools.protoc --proto_path=. --python_out=. --grpc_python_out=. $protoFiles
      - name: Build protobuf (Linux)
        if: matrix.os == 'ubuntu-latest'
        working-directory: cims
        run: |
          find Protobuf -type f -name "*.proto" | xargs python -m grpc_tools.protoc --proto_path=. --python_out=. --grpc_python_out=.

      - name: Install Linux-specific Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y mold clang

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        uses: Nuitka/Nuitka-Action@main
        env:
          NUITKA_CACHE_DIR: ${{ runner.temp }}\\nuitka-cache
        with:
          script-name: cims/CIMS.py
          output-file: CIMS-backend
          include-package-data: cims
          disable-console: false
          product-name: CIMS-backend
          file-version: 2.0.0.0
          product-version: 2.0.0.0

      - name: Build (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: Nuitka/Nuitka-Action@main
        env:
          CC: clang
          CXX: clang++
          LDFLAGS: "-fuse-ld=mold"
        with:
          script-name: cims/CIMS.py
          output-file: CIMS-backend
          include-package-data: cims
          product-name: CIMS-backend

      - name: Upload unsigned application
        uses: actions/upload-artifact@v4
        with:
          name: CIMS-backend-${{ matrix.os }}
          path: build/CIMS.dist
